// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDwuQhABtSOhn3nU5iENZUOdCiM-Set8zg',
    appId: '1:489764144944:web:4dda4b212c906039b5aaf5',
    messagingSenderId: '489764144944',
    projectId: 'women-safety-14fe6',
    authDomain: 'women-safety-14fe6.firebaseapp.com',
    storageBucket: 'women-safety-14fe6.firebasestorage.app',
    measurementId: 'G-GG2EL91W61',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCDDYFc_iFpdFqFLQPRev4kgg4sgaR5M3o',
    appId: '1:489764144944:android:422cd2c4c4dc9cf6b5aaf5',
    messagingSenderId: '489764144944',
    projectId: 'women-safety-14fe6',
    storageBucket: 'women-safety-14fe6.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCCiWUZ8Lw9NLvuqNRH_sLkXVpSOcvoDDw',
    appId: '1:489764144944:ios:4695250f7f0cdefcb5aaf5',
    messagingSenderId: '489764144944',
    projectId: 'women-safety-14fe6',
    storageBucket: 'women-safety-14fe6.firebasestorage.app',
    iosBundleId: 'com.example.samasoc',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyCCiWUZ8Lw9NLvuqNRH_sLkXVpSOcvoDDw',
    appId: '1:489764144944:ios:4695250f7f0cdefcb5aaf5',
    messagingSenderId: '489764144944',
    projectId: 'women-safety-14fe6',
    storageBucket: 'women-safety-14fe6.firebasestorage.app',
    iosBundleId: 'com.example.samasoc',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDwuQhABtSOhn3nU5iENZUOdCiM-Set8zg',
    appId: '1:489764144944:web:a63b20484499ce4db5aaf5',
    messagingSenderId: '489764144944',
    projectId: 'women-safety-14fe6',
    authDomain: 'women-safety-14fe6.firebaseapp.com',
    storageBucket: 'women-safety-14fe6.firebasestorage.app',
    measurementId: 'G-FFVSR6H292',
  );
}
